title: 考試經驗與心得
email: tobywang2021@gmail.com
description: >-
  Recordings of high-quality exam parsing insights, including essay reference answers and study notes.
baseurl: "/ai-exp-exam" # the subpath of your site, e.g. /blog
url: "https://toydogcat.github.io" # the base hostname & protocol for your site
github_username:  toydogcat

# Build settings
remote_theme: a-chacon/wind
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Agency colors or categories can be defined here
categories: [post-office, taipower, cht]
